.\" Manpage for trans
.\" contact charlottewaterhouse70@gmail.com to correct typos and errors
.TH man 1 "05 july 2021" "1.0" "trans man page"
.SH Trans
trans \- print out a string coloured as the trans flag
.SH SYNOPSIS
trans "[STRING]"
.SH DESCRIPTION
trans is a program that prints out a string coloured as the trans flag it prints"██████████████████"
by default
.SH OPTIONS
trans takes one argument of the string you want to print e.g. trans "hello world"
.SH BUGS
No known bugs.
.SH AUTHOR
charlotte waterhouse (charlottewaterhouse70@gmail.com)
